export const ipcChannels = {
  appGetHealth: "app:get-health",
  appRunClaudeDemo: "app:run-claude-demo",
  appListSessionEvents: "app:list-session-events",
  appStartBrainstorm: "app:start-brainstorm",
  appReviseBrainstorm: "app:revise-brainstorm",
  appAnswerQuestion: "app:answer-question",
  appStartTaskExecution: "app:start-task-execution",
  appListTasks: "app:list-tasks",
  appGetProjectStats: "app:get-project-stats",
  appGetLatestSpec: "app:get-latest-spec",
  appReviewTask: "app:review-task",
  projectsList: "projects:list",
  projectsValidatePath: "projects:validate-path",
  projectsSelectDirectory: "projects:select-directory",
  projectsCreate: "projects:create",
  projectsUpdate: "projects:update",
  projectsArchive: "projects:archive",
} as const;
